### ISSUE TITLE
CUDA error : no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by summertube** [SciSharp/LLamaSharp#162]
I've successfully run the model using the CPU backend, but switching to the CUDA 11 backend is causing an error. 
Interestingly, my computer can execute the same model when using the llama-cppy-python with the cuBLAS backend.

My computer setup

======================================================

Cpu : Intel(R) Xeon(R) (14 cores, 28 logical processors)
RAM : 64 GB
OS  : Windows 10 x64
Device 0: Quadro P400, compute capability 6.1
Device 1: Quadro K620, compute capability 5.0

======================================================

Visual studio

=======================================

Visual studio 2022
Net 6.0
LLamaSharp(0.51)
LLamaSharp.Backend.Cuda11(0.51)
Cuda toolkit installed: 11.7

Model : llama-2-7b-guanaco-qlora.Q4_K_M.gguf
https://huggingface.co/TheBloke/llama-2-7B-Guanaco-QLoRA-GGUF

Console app with ChatSessionStripRoleName.cs example
           var parameters = new ModelParams(modelPath)
           {
               GpuLayerCount = 2,
               LowVram = true,
               ContextSize = 1024,
               BatchSize = 512,
               Threads = 18,
               Seed = 1337,
               UseMemoryLock = true
           };

=========================================

Error Message

=========================================

llama_new_context_with_model: kv self size  =  800.00 MB
llama_new_context_with_model: compute buffer total size =  111.41 MB
llama_new_context_with_model: not allocating a VRAM scratch buffer due to low VRAM option
The chat session has started. The role names won't be printed.
Transcript of a dialog, where the User interacts with an Assistant named Bob. Bob is helpful, kind, honest, good at writing, and never fails to answer the User's requests immediately and with precision.

User: Hello, Bob.
Bob: Hello. How may I help you today?
User: Please tell me the largest city in Europe.
Bob: Sure. The largest city in Europe is Moscow, the capital of Russia.

User:CUDA error 209 at D:\a\LLamaSharp\LLamaSharp\ggml-cuda.cu:6041: no kernel image is available for execution on the device

=============================================

**Comment by summertube** [comment]
I've recompiled the llama.cpp project using CMake with the following commands:

+++++++++++++++++++++++++++++++++++++++++++++++++++

mkdir build
cd build
cmake .. -DLLAMA_CUBLAS=ON -DBUILD_SHARED_LIBS=ON
cmake --build . --config Release

+++++++++++++++++++++++++++++++++++++++++++++++++++++

Afterwards, I replaced the existing libllama.dll file in the /bin/debug/.../ directory with the newly compiled one (llama.dll). 
Unfortunately, I'm still encountering the same error message.

**Comment by martindevans** [comment]
I don't really know a lot about CUDA, so I'm not sure how much I can help debug this.

The error "no kernel image is available for execution on the device" seems to mean that the library was not compiled with support for your device. From [this issue](https://github.com/ggerganov/ggml/issues/465) that probably means you need to adjust the build script to add some additional architectures to support your specific hardware.

**Comment by summertube** [comment]
Thanks! The issue has been resolved. It turns out that the problem was due to the compute capability of my Quadro K620, which is 5.0(50). The CMake configuration was initially set to support version 5.2(52) and up, hence the mismatch.

https://en.wikipedia.org/wiki/CUDA

Cuda toolkit 11.7 support 

Changed CMakeLists.txt
+++++++++++++++++++++++++++++++++++++++++++++++
compute capability 5.0 (50)  is working with cuda 11. may be with cuda 12
+++++++++++++++++++++++++++++++++++++++++++++++
From :
set(CMAKE_CUDA_ARCHITECTURES "52;61;70") # lowest CUDA 12 standard + lowest for integer .......

To:
set(CMAKE_CUDA_ARCHITECTURES "50;52;61;70") # Added 50 for Maxwell early version 
+++++++++++++++++++++++++++++++++++++++++++++++++++

Recompiled and copied the "llama.cpp\build\bin\\Release\llama.dll" to "myproject\bin\x64\Debug\net6.0\runtimes\win-x64\native\libllama.dll"
