### ISSUE TITLE
[LLamaSharp.Backend.Cuda12 v0.10.0] Unable to load the model onto multiple GPUs

### ISSUE THREAD

**Issue by ChengYen-Tang** [SciSharp/LLamaSharp#617]
In version `cuda12 v0.10.0`, the model will only load onto a single GPU, resulting in `cudaMalloc failed: out of memory`
There is no such issue in `cuda12 v0.9.1`.
OS: Ubuntu22.04

![image](https://github.com/SciSharp/LLamaSharp/assets/32535494/818f7e71-4e40-4371-ba84-5944329c97ef)
![image](https://github.com/SciSharp/LLamaSharp/assets/32535494/3aed8258-bdf2-4c68-ac46-d1ecc2388f7d)

**Comment by martindevans** [comment]
There was a new "GPU Split Mode" parameter introduced in 0.10.0, see [here](https://github.com/SciSharp/LLamaSharp/blob/master/LLama/Common/ModelParams.cs#L18-L22).

I don't use multiple GPU inference myself, but I would guess you need to set that to something other than "None" when loading the model.

**Comment by ChengYen-Tang** [comment]
Thanks, I will try it tomorrow.

**Comment by ChengYen-Tang** [comment]
Thank you, it worked
